version: '3'
services:
  amqp:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
  pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
